apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-app
    tier: db-tier
spec:
  selector:
    name: redis-pod
    app: demo-app
    tier: db-tier
  ports:
  - port: 6379
    targetPort: 6379
