apiVersion: v1
kind: ReplicaSet
metadata:
  name: my-replica
  labels: 
    app: replica
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: nginx
      labels:
        app: web-server
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
