apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: prod
    tier: back
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: web-server
      tier: frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        app:  web-server
        tier: frontend
    spec:
      containers:
        - name: nginx
          image:  nginx
      restartPolicy: Never
      resources: