apiVersion: v1
kind: Pod
metadata:
  name: multi
  labels:
    name: multi
spec:
  containers:
  - name: first
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: log-volume
        mountPath: /logs/
    ports:
      - containerPort: 80
  - name: 2nd
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
    volumeMounts:
      - name: log-volume
        mountPath: /var/log/events/
  volumes:
    - name:  log-volume
      hostPath:  /var/log/webapp/
