apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-demo
  namespace: test
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    

---

apiVersion: v1
kind: Pod
metadata:
  name: game-demo
  namespace: test
  labels: 
    env: test
    app: game
spec:
  containers:
    - image:  demo-game
      name:  demo-game
      env:
        - name:  PLAYER_INITIAL_LIVES
          valueFrom: 
            configMapRefKey:
              name: config-demo
              key: player_initial_lives
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom: 
            configMapRefKey:
              name: config-demo
              key: ui_properties_file_name
      volumeMounts: 
      - name: config_vol
        mountPath: "/config"
      resources:
  volumes: 
  - name: config_vol
    configmap: 
      name: config-demo
      items: 
      - key: "game.properties"
        path: "game.properties"
      - key: "user-interface.properties"
        path: "user-interface.properties"

